import { BaseViewModel } from "../internal/base.viewmodel";

export class commonConverterViewModel implements BaseViewModel {
  PageTitle: string = "";
  weeks!: number | undefined;
  frequency!: number | null;
  isFrequency!: boolean;
  hertz!: number | undefined;
  kilohertz!: number | undefined;
  milliseconds!: number | undefined;
  nanoseconds!: number | undefined;
  microseconds!: number | undefined;
  megahertz!: number | undefined;
  gegahertz!: number | undefined;
  kilometerperhour!: number | undefined;
  isTime!: boolean;
  time!: number | null;
  days!: number | undefined;
  seconds!: number | undefined;
  years!: number | undefined;
  months!: number | undefined;
  decades!: number | undefined;
  minutes!: number | undefined;
  hours!: number | undefined;
  cubicKilometer!: number | undefined;
  weight!: number | undefined;
  ads!: boolean;
  kilograms!: number | undefined;
  grams!: number | undefined;
  pounds!: number | undefined;
  tons!: number | undefined;
  ounces!: number | undefined;
  stones!: number | undefined;
  milligrams!: number | undefined;
  quintal!: number | undefined;
  micrograms!: number | undefined;
  volume!: number | null;
  cubicCentimeter!: number | undefined;
  cubicMillimeter!: number | undefined;
  cubicFeet!: number | undefined;
  cubicInch!: number | undefined;
  liter!: number | undefined;
  milliliter!: number | undefined;
  usGallon!: number | undefined;
  ukGallon!: number | undefined;
  cubicMeter!: number | undefined;
  length!: number | null;
  meter!: number | undefined;
  kilometer!: number | undefined;
  centimeter!: number | undefined;
  millimeter!: number | undefined;
  speed!: number | null;
  meterPerSecond!: number | undefined;
  temperature!: number | null;
  celsius!: number | undefined;
  kelvin!: number | undefined;
  fahrenheit!: number | undefined;
  kilometerPerSecond!: number | undefined;
  milesPerHour!: number | undefined;
  feetPerSecond!: number | undefined;
  knots!: number | undefined;
  micrometer!: number | undefined;
  nanometer!: number | undefined;
  inch!: number | undefined;
  feet!: number | undefined;
  yard!: number | undefined;
  miles!: number | undefined;
  title: string = "";
  sno: number = 0;
  receivedSearchValue: string = "";
  filteredCommonConverters: any[] = [];
  commonConverters: any[] = [];
  isWeight!: boolean;
  isSpeed!: boolean;
  isArea!: boolean;
  isLength!: boolean;
  isTemperature!: boolean;
  isVolume!: boolean;
  weightIsFavorite!: boolean;
  // area
  area: number | undefined;
  targetUnit: string = "";
  squareMeter: number | undefined;
  squareKM: number | undefined;
  squareFeet: number | undefined;
  acre: number | undefined;
  hectare: number | undefined;
  squareMile: number | undefined;
  squareYard: number | undefined;
  //
  isFavorite!: boolean;
  imgSrc: string = "";
  searchArrayFromCommonConverters: string[] = [];
  isSelected: boolean = false;
  selectedItem: any;
  defaultSelectedItem: any;
  currency!: number | null;
  apiData: any;
  listOfRatesAndValues: any[] = [];
  convertedAmounts: { [key: string]: number } = {}; // Store converted amounts for each currency
  currencyRatesObject: any;
  targetRates: any;
  convertedRatesArray: any[] = [];

  searchInput!: string;
  filteredArray: any[] = [];
  formattedDate!: string;
}
